import requests

# Define the URL of the Flask server
url = "http://localhost:5000/chat"

# Set the query and conversation_id
query = "Hello, how are you?"
conversation_id = "your-conversation-id-here"  # If no conversation ID, it will be generated by the Flask server

# Create the request parameters
params = {
    'query': query,
    'conversation_id': conversation_id  # You can omit this if you want the server to generate it
}

# Send the GET request to the Flask server
response = requests.get(url, params=params, stream=True)

# Check if the request was successful
if response.status_code == 200:
    # Print the response content
    print("Chatbot Response:")
    for chunk in response.iter_lines():
        if chunk:
            print(chunk.decode('utf-8'))
else:
    print(f"Error: {response.status_code}")
